/* eslint-disable react-hooks/exhaustive-deps */
import {FC, useContext, useState, useEffect, useMemo} from 'react'
import {useQuery} from 'react-query'
import {
  createResponseContext,
  initialQueryResponse,
  initialQueryState,
  PaginationState,
  QUERIES,
  stringifyRequestQuery,
  WithChildren,
} from '../../../../../../_metronic/helpers'
import {getUsers} from './_requests'
import {User} from './_models'
import {useQueryRequest} from './QueryRequestProvider'

const QueryResponseContext = createResponseContext<User>(initialQueryResponse)
const QueryResponseProvider: FC<WithChildren> = ({children}) => {
  const {state} = useQueryRequest()
  const [query, setQuery] = useState<string>(stringifyRequestQuery(state))
  const updatedQuery = useMemo(() => stringifyRequestQuery(state), [state])

  useEffect(() => {
    if (query !== updatedQuery) {
      setQuery(updatedQuery)
    }
  }, [updatedQuery])

  const {
    isFetching,
    refetch,
    data: response,
  } = useQuery(
    `${QUERIES.USERS_LIST}-${query}`,
    () => {
      return getUsers(query)
    },
    {cacheTime: 0, keepPreviousData: true, refetchOnWindowFocus: false}
  )

  return (
    <QueryResponseContext.Provider value={{isLoading: isFetching, refetch, response, query}}>
      {children}
    </QueryResponseContext.Provider>
  )
}

const useQueryResponse = () => useContext(QueryResponseContext)

const useQueryResponseData = (maxValue: any = '') => {
  const {response} = useQueryResponse()
  if (!response) {
    return []
  }

  // return response?.data || []
  return maxValue ? mockedData.data.slice(0, +maxValue) : mockedData.data
}

const useQueryResponsePagination = () => {
  const defaultPaginationState: PaginationState = {
    links: [],
    ...initialQueryState,
  }

  const {response} = useQueryResponse()
  if (!response || !response.payload || !response.payload.pagination) {
    return defaultPaginationState
  }

  return response.payload.pagination
}

const useQueryResponseLoading = (): boolean => {
  const {isLoading} = useQueryResponse()
  return isLoading
}

export {
  QueryResponseProvider,
  useQueryResponse,
  useQueryResponseData,
  useQueryResponsePagination,
  useQueryResponseLoading,
}

const mockedData: any = {
  data: [
    {
      id: 1,
      dispatchId: 'DES/12-034334',
      dispatchPlant: 'Ocean Hub 6',
      collectorId: 'OID_IND_PNQ_00123',
      supplyId: '2354556',
      address: '123, Freak Street, Indonesia',
      bags: 3,
      creationDate: '10/08/2022',
      shift: 'A',
      inCharge: 'John Smith',
      processName: 'Sorting',
      inputQuantitySorted: '2300',
      type1: '200 kg',
      type2: '1200 kg',
      type: '0 kg',
      createdBy: 'Om',
      plasticType: 'BOP Blue',
      pickupDate: '12/08/2023',
      driverOid: 'OID_IND_PNQ_00129',
      vehicleNumber: 'IND 7071',
      recivedBy: 'Sujan',
      recivedAt: 'Ocean Hub 6',
      reciverOid: 'OID_IND_PNQ_00878',
      inpectedBy: 'Nirmal',
      weight: '5 Kg',
      deduction: '3 Kg',
      netRecivedBy: '2 Kg',
      materialValue: '23 USD',
      paymentDate: '30/08/2023',
      mobileNumber: '31621274594',
      addrOne: 'Mohta Building, Bhikaji Cama Place, Delhi',
      townCity: 'Chennai',
      latitude: '28.34',
      dropOffPoint: 'Pulchowk',
      longitude: '54.32',
      operationDays: '3',
      operatingHours: '5',
      code: '3454',
      managerName: 'Narahari Sijapati',
      manager: 'Yes',
      startTime: '9:12 am',
      endTime: '5:00 pm',
      country: 'India',
      zipCode: '600079',
      landMark: '16, Krishna Iyer St',
      addrTwo: 'Lakkidi P.O, Kerala',
      name: 'Emma Smith',
      avatar: 'avatars/300-6.jpg',
      email: 'smith@kpmg.com',
      position: 'Art Director',
      role: 'Administrator',
      last_login: 'Yesterday',
      two_steps: false,
      joined_day: '10 Nov 2022, 9:23 pm',
      online: false,
      materialDispatched: 'HDPE',
    },
    {
      id: 2,
      dispatchId: 'DES/12-034334',
      dispatchPlant: 'Ocean Hub 6',
      collectorId: 'OID_IND_PNQ_00123',

      supplyId: '2354556',
      address: '123, Freak Street, Indonesia',
      bags: 3,
      creationDate: '10/08/2022',
      shift: 'A',
      inCharge: 'John Smith',
      processName: 'Sorting',
      inputQuantitySorted: '2300',
      type1: '200 kg',
      type2: '1200 kg',
      type: '0 kg',
      createdBy: 'Om',
      plasticType: 'BOP Blue',
      pickupDate: '12/08/2023',
      driverOid: 'OID_IND_PNQ_00129',
      vehicleNumber: 'IND 7071',
      recivedBy: 'Sujan',
      recivedAt: 'Ocean Hub 6',
      reciverOid: 'OID_IND_PNQ_00878',
      inpectedBy: 'Nirmal',
      weight: '5 Kg',
      deduction: '3 Kg',
      netRecivedBy: '2 Kg',
      materialValue: '23 USD',
      paymentDate: '30/08/2023',
      mobileNumber: '31621274594',
      addrOne: 'Mohta Building, Bhikaji Cama Place, Delhi',
      townCity: 'Chennai',
      latitude: '28.34',
      dropOffPoint: 'Pulchowk',
      longitude: '54.32',
      operationDays: '3',
      operatingHours: '5',
      code: '3454',
      managerName: 'Narahari Sijapati',
      manager: 'Yes',
      startTime: '9:12 am',
      endTime: '5:00 pm',
      country: 'India',
      zipCode: '600079',
      landMark: '16, Krishna Iyer St',
      addrTwo: 'Lakkidi P.O, Kerala',
      name: 'Melody Macy',
      initials: {
        label: 'M',
        state: 'danger',
      },
      email: 'melody@altbox.com',
      position: 'Marketing Analytic',
      role: 'Analyst',
      last_login: '20 mins ago',
      two_steps: true,
      joined_day: '10 Nov 2022, 8:43 pm',
      online: false,
      materialDispatched: 'HDPE',
    },
    {
      id: 3,
      dispatchId: 'DES/12-034334',
      dispatchPlant: 'Ocean Hub 6',
      collectorId: 'OID_IND_PNQ_00123',
      supplyId: '2354556',
      address: '123, Freak Street, Indonesia',
      bags: 3,
      creationDate: '20/08/2022',
      shift: 'A',
      inCharge: 'John Smith',
      processName: 'Sorting',
      inputQuantitySorted: '2300',
      type1: '200 kg',
      type2: '1200 kg',
      type: '0 kg',
      createdBy: 'Om',
      plasticType: 'BOP Blue',
      pickupDate: '24/08/2023',
      driverOid: 'OID_IND_PNQ_00129',
      vehicleNumber: 'IND 7071',
      recivedBy: 'Sujan',
      recivedAt: 'Ocean Hub 6',
      reciverOid: 'OID_IND_PNQ_00878',
      inpectedBy: 'Nirmal',
      weight: '5 Kg',
      deduction: '3 Kg',
      netRecivedBy: '2 Kg',
      materialValue: '23 USD',
      paymentDate: '30/08/2023',
      mobileNumber: '31621274594',
      addrOne: 'Mohta Building, Bhikaji Cama Place, Delhi',
      townCity: 'Chennai',
      latitude: '28.34',
      dropOffPoint: 'Pulchowk',
      longitude: '54.32',
      operationDays: '3',
      operatingHours: '5',
      code: '3454',
      managerName: 'Narahari Sijapati',
      manager: 'Yes',
      startTime: '9:12 am',
      endTime: '5:00 pm',
      country: 'India',
      zipCode: '600079',
      landMark: '16, Krishna Iyer St',
      addrTwo: 'Lakkidi P.O, Kerala',
      name: 'Max Smith',
      avatar: 'avatars/300-1.jpg',
      email: 'max@kt.com',
      position: 'Software Enginer',
      role: 'Developer',
      last_login: '3 days ago',
      two_steps: false,
      joined_day: '22 Sep 2022, 8:43 pm',
      online: false,
      materialDispatched: 'HDPE',
    },
    {
      id: 4,
      dispatchId: 'DES/12-034334',
      dispatchPlant: 'Ocean Hub 6',
      collectorId: 'OID_IND_PNQ_00123',
      supplyId: '2354556',
      address: '123, Freak Street, Indonesia',
      bags: 3,
      creationDate: '10/08/2022',
      shift: 'A',
      inCharge: 'John Smith',
      processName: 'Sorting',
      inputQuantitySorted: '2300',
      type1: '200 kg',
      type2: '1200 kg',
      type: '0 kg',
      createdBy: 'Om',
      plasticType: 'BOP Blue',
      pickupDate: '12/08/2023',
      driverOid: 'OID_IND_PNQ_00129',
      vehicleNumber: 'IND 7071',
      recivedBy: 'Sujan',
      recivedAt: 'Ocean Hub 6',
      reciverOid: 'OID_IND_PNQ_00878',
      inpectedBy: 'Nirmal',
      weight: '5 Kg',
      deduction: '3 Kg',
      netRecivedBy: '2 Kg',
      materialValue: '23 USD',
      paymentDate: '30/08/2023',
      mobileNumber: '31621274594',
      addrOne: 'Mohta Building, Bhikaji Cama Place, Delhi',
      townCity: 'Chennai',
      latitude: '28.34',
      dropOffPoint: 'Pulchowk',
      longitude: '54.32',
      operationDays: '3',
      operatingHours: '5',
      code: '3454',
      managerName: 'Narahari Sijapati',
      manager: 'Yes',
      startTime: '9:12 am',
      endTime: '5:00 pm',
      country: 'India',
      zipCode: '600079',
      landMark: '16, Krishna Iyer St',
      addrTwo: 'Lakkidi P.O, Kerala',
      name: 'Sean Bean',
      avatar: 'avatars/300-5.jpg',
      email: 'sean@dellito.com',
      position: 'Web Developer',
      role: 'Support',
      last_login: '5 hours ago',
      two_steps: true,
      joined_day: '21 Feb 2022, 6:43 am',
      online: false,
      materialDispatched: 'HDPE',
    },
    {
      id: 5,
      dispatchId: 'DES/12-034334',
      dispatchPlant: 'Ocean Hub 6',
      collectorId: 'OID_IND_PNQ_00123',
      supplyId: '2354556',
      address: '123, Freak Street, Indonesia',
      bags: 3,
      creationDate: '10/08/2022',
      shift: 'A',
      inCharge: 'John Smith',
      processName: 'Sorting',
      inputQuantitySorted: '2300',
      type1: '200 kg',
      type2: '1200 kg',
      type: '0 kg',
      createdBy: 'Om',
      plasticType: 'BOP Blue',
      pickupDate: '12/08/2023',
      driverOid: 'OID_IND_PNQ_00129',
      vehicleNumber: 'IND 7071',
      recivedBy: 'Sujan',
      recivedAt: 'Ocean Hub 6',
      reciverOid: 'OID_IND_PNQ_00878',
      inpectedBy: 'Nirmal',
      weight: '5 Kg',
      deduction: '3 Kg',
      netRecivedBy: '2 Kg',
      materialValue: '23 USD',
      paymentDate: '30/08/2023',
      mobileNumber: '31621274594',
      addrOne: 'Mohta Building, Bhikaji Cama Place, Delhi',
      townCity: 'Chennai',
      latitude: '28.34',
      dropOffPoint: 'Pulchowk',
      longitude: '54.32',
      operationDays: '3',
      operatingHours: '5',
      code: '3454',
      managerName: 'Narahari Sijapati',
      manager: 'Yes',
      startTime: '9:12 am',
      endTime: '5:00 pm',
      country: 'India',
      zipCode: '600079',
      landMark: '16, Krishna Iyer St',
      addrTwo: 'Lakkidi P.O, Kerala',
      name: 'Brian Cox',
      avatar: 'avatars/300-25.jpg',
      email: 'brian@exchange.com',
      position: 'UI/UX Designer',
      role: 'Developer',
      last_login: '2 days ago',
      two_steps: true,
      joined_day: '10 Mar 2022, 9:23 pm',
      online: false,
      materialDispatched: 'HDPE',
    },
    {
      id: 6,
      dispatchId: 'DES/12-034334',
      dispatchPlant: 'Ocean Hub 6',
      collectorId: 'OID_IND_PNQ_00123',
      supplyId: '2354556',
      address: '123, Freak Street, Indonesia',
      bags: 3,
      creationDate: '10/08/2022',
      shift: 'A',
      inCharge: 'John Smith',
      processName: 'Sorting',
      inputQuantitySorted: '2300',
      type1: '200 kg',
      type2: '1200 kg',
      type: '0 kg',
      createdBy: 'Om',
      plasticType: 'BOP Blue',
      pickupDate: '12/08/2023',
      driverOid: 'OID_IND_PNQ_00129',
      vehicleNumber: 'IND 7071',
      recivedBy: 'Sujan',
      recivedAt: 'Ocean Hub 6',
      reciverOid: 'OID_IND_PNQ_00878',
      inpectedBy: 'Nirmal',
      weight: '5 Kg',
      deduction: '3 Kg',
      netRecivedBy: '2 Kg',
      materialValue: '23 USD',
      paymentDate: '30/08/2023',
      mobileNumber: '31621274594',
      addrOne: 'Mohta Building, Bhikaji Cama Place, Delhi',
      townCity: 'Chennai',
      latitude: '28.34',
      dropOffPoint: 'Pulchowk',
      longitude: '54.32',
      operationDays: '3',
      operatingHours: '5',
      code: '3454',
      managerName: 'Narahari Sijapati',
      manager: 'Yes',
      startTime: '9:12 am',
      endTime: '5:00 pm',
      country: 'India',
      zipCode: '600079',
      landMark: '16, Krishna Iyer St',
      addrTwo: 'Lakkidi P.O, Kerala',
      name: 'Mikaela Collins',
      initials: {
        label: 'M',
        state: 'warning',
      },
      email: 'mik@pex.com',
      position: 'Head Of Marketing',
      role: 'Administrator',
      last_login: '5 days ago',
      two_steps: false,
      joined_day: '20 Dec 2022, 10:10 pm',
      online: false,
      materialDispatched: 'HDPE',
    },
    {
      id: 7,
      dispatchId: 'DES/12-034334',
      dispatchPlant: 'Ocean Hub 6',
      collectorId: 'OID_IND_PNQ_00123',
      supplyId: '2354556',
      address: '123, Freak Street, Indonesia',
      bags: 3,
      creationDate: '10/08/2022',
      shift: 'A',
      inCharge: 'John Smith',
      processName: 'Sorting',
      inputQuantitySorted: '2300',
      type1: '200 kg',
      type2: '1200 kg',
      type: '0 kg',
      createdBy: 'Om',
      plasticType: 'BOP Blue',
      pickupDate: '12/08/2023',
      driverOid: 'OID_IND_PNQ_00129',
      vehicleNumber: 'IND 7071',
      recivedBy: 'Sujan',
      recivedAt: 'Ocean Hub 6',
      reciverOid: 'OID_IND_PNQ_00878',
      inpectedBy: 'Nirmal',
      weight: '5 Kg',
      deduction: '3 Kg',
      netRecivedBy: '2 Kg',
      materialValue: '23 USD',
      paymentDate: '30/08/2023',
      mobileNumber: '31621274594',
      addrOne: 'Mohta Building, Bhikaji Cama Place, Delhi',
      townCity: 'Chennai',
      latitude: '28.34',
      dropOffPoint: 'Pulchowk',
      longitude: '54.32',
      operationDays: '3',
      operatingHours: '5',
      code: '3454',
      managerName: 'Narahari Sijapati',
      manager: 'Yes',
      startTime: '9:12 am',
      endTime: '5:00 pm',
      country: 'India',
      zipCode: '600079',
      landMark: '16, Krishna Iyer St',
      addrTwo: 'Lakkidi P.O, Kerala',
      name: 'Francis Mitcham',
      avatar: 'avatars/300-9.jpg',
      email: 'f.mit@kpmg.com',
      position: 'Software Arcitect',
      role: 'Trial',
      last_login: '3 weeks ago',
      two_steps: false,
      joined_day: '10 Nov 2022, 6:43 am',
      online: false,
      materialDispatched: 'HDPE',
    },
    {
      id: 8,
      dispatchId: 'DES/12-034334',
      dispatchPlant: 'Ocean Hub 6',
      collectorId: 'OID_IND_PNQ_00123',
      supplyId: '2354556',
      address: '123, Freak Street, Indonesia',
      bags: 3,
      creationDate: '10/08/2022',
      shift: 'A',
      inCharge: 'John Smith',
      processName: 'Sorting',
      inputQuantitySorted: '2300',
      type1: '200 kg',
      type2: '1200 kg',
      type: '0 kg',
      createdBy: 'Om',
      plasticType: 'BOP Blue',
      pickupDate: '12/08/2023',
      driverOid: 'OID_IND_PNQ_00129',
      vehicleNumber: 'IND 7071',
      recivedBy: 'Sujan',
      recivedAt: 'Ocean Hub 6',
      reciverOid: 'OID_IND_PNQ_00878',
      inpectedBy: 'Nirmal',
      weight: '5 Kg',
      deduction: '3 Kg',
      netRecivedBy: '2 Kg',
      materialValue: '23 USD',
      paymentDate: '30/08/2023',
      mobileNumber: '31621274594',
      addrOne: 'Mohta Building, Bhikaji Cama Place, Delhi',
      townCity: 'Chennai',
      latitude: '28.34',
      dropOffPoint: 'Pulchowk',
      longitude: '54.32',
      operationDays: '3',
      operatingHours: '5',
      code: '3454',
      managerName: 'Narahari Sijapati',
      manager: 'Yes',
      startTime: '9:12 am',
      endTime: '5:00 pm',
      country: 'India',
      zipCode: '600079',
      landMark: '16, Krishna Iyer St',
      addrTwo: 'Lakkidi P.O, Kerala',
      name: 'Olivia Wild',
      initials: {
        label: 'O',
        state: 'danger',
      },
      email: 'olivia@corpmail.com',
      position: 'System Admin',
      role: 'Administrator',
      last_login: 'Yesterday',
      two_steps: false,
      joined_day: '19 Aug 2022, 11:05 am',
      online: false,
      materialDispatched: 'HDPE',
    },
    {
      id: 9,
      dispatchId: 'DES/12-034334',
      dispatchPlant: 'Ocean Hub 6',
      collectorId: 'OID_IND_PNQ_00123',
      supplyId: '2354556',
      address: '123, Freak Street, Indonesia',
      bags: 3,
      creationDate: '10/08/2022',
      shift: 'A',
      inCharge: 'John Smith',
      processName: 'Sorting',
      inputQuantitySorted: '2300',
      type1: '200 kg',
      type2: '1200 kg',
      type: '0 kg',
      createdBy: 'Om',
      plasticType: 'BOP Blue',
      pickupDate: '12/08/2023',
      driverOid: 'OID_IND_PNQ_00129',
      vehicleNumber: 'IND 7071',
      recivedBy: 'Sujan',
      recivedAt: 'Ocean Hub 6',
      reciverOid: 'OID_IND_PNQ_00878',
      inpectedBy: 'Nirmal',
      weight: '5 Kg',
      deduction: '3 Kg',
      netRecivedBy: '2 Kg',
      materialValue: '23 USD',
      paymentDate: '30/08/2023',
      mobileNumber: '31621274594',
      addrOne: 'Mohta Building, Bhikaji Cama Place, Delhi',
      townCity: 'Chennai',
      latitude: '28.34',
      dropOffPoint: 'Pulchowk',
      longitude: '54.32',
      operationDays: '3',
      operatingHours: '5',
      code: '3454',
      managerName: 'Narahari Sijapati',
      manager: 'Yes',
      startTime: '9:12 am',
      endTime: '5:00 pm',
      country: 'India',
      zipCode: '600079',
      landMark: '16, Krishna Iyer St',
      addrTwo: 'Lakkidi P.O, Kerala',
      name: 'Neil Owen',
      initials: {
        label: 'N',
        state: 'primary',
      },
      email: 'owen.neil@gmail.com',
      position: 'Account Manager',
      role: 'Analyst',
      last_login: '20 mins ago',
      two_steps: true,
      joined_day: '25 Oct 2022, 10:30 am',
      online: false,
      materialDispatched: 'HDPE',
    },
    {
      id: 10,
      dispatchId: 'DES/12-034334',
      dispatchPlant: 'Ocean Hub 6',
      collectorId: 'OID_IND_PNQ_00123',
      supplyId: '2354556',
      address: '123, Freak Street, Indonesia',
      bags: 3,
      creationDate: '10/08/2022',
      shift: 'A',
      inCharge: 'John Smith',
      processName: 'Sorting',
      inputQuantitySorted: '2300',
      type1: '200 kg',
      type2: '1200 kg',
      type: '0 kg',
      createdBy: 'Om',
      plasticType: 'BOP Blue',
      pickupDate: '12/08/2023',
      driverOid: 'OID_IND_PNQ_00129',
      vehicleNumber: 'IND 7071',
      recivedBy: 'Sujan',
      recivedAt: 'Ocean Hub 6',
      reciverOid: 'OID_IND_PNQ_00878',
      inpectedBy: 'Nirmal',
      weight: '5 Kg',
      deduction: '3 Kg',
      netRecivedBy: '2 Kg',
      materialValue: '23 USD',
      paymentDate: '30/08/2023',
      mobileNumber: '31621274594',
      addrOne: 'Mohta Building, Bhikaji Cama Place, Delhi',
      townCity: 'Chennai',
      latitude: '28.34',
      dropOffPoint: 'Pulchowk',
      longitude: '54.32',
      operationDays: '3',
      operatingHours: '5',
      code: '3454',
      managerName: 'Narahari Sijapati',
      manager: 'Yes',
      startTime: '9:12 am',
      endTime: '5:00 pm',
      country: 'India',
      zipCode: '600079',
      landMark: '16, Krishna Iyer St',
      addrTwo: 'Lakkidi P.O, Kerala',
      name: 'Dan Wilson',
      avatar: 'avatars/300-23.jpg',
      email: 'dam@consilting.com',
      position: 'Web Desinger',
      role: 'Developer',
      last_login: '3 days ago',
      two_steps: false,
      joined_day: '19 Aug 2022, 10:10 pm',
      online: false,
      materialDispatched: 'HDPE',
    },
  ],
  payload: {
    pagination: {
      page: 1,
      first_page_url: '/?page=1',
      from: 1,
      last_page: 3,
      links: [
        {
          url: null,
          label: '&laquo; Previous',
          active: false,
          page: null,
        },
        {
          url: '/?page=1',
          label: '1',
          active: true,
          page: 1,
        },
        {
          url: '/?page=2',
          label: '2',
          active: false,
          page: 2,
        },
        {
          url: '/?page=3',
          label: '3',
          active: false,
          page: 3,
        },
        {
          url: '/?page=2',
          label: 'Next &raquo;',
          active: false,
          page: 2,
        },
      ],
      next_page_url: '/?page=2',
      size: '10',
      prev_page_url: null,
      to: 10,
      total: 21,
    },
  },
}
