export const countryList = [
  {value: 'Afghanistan', label: 'Afghanistan (93)', code: '93'},
  {value: 'Aland Islands', label: 'Aland Islands (+358-18)', code: '+358-18'},
  {value: 'Albania', label: 'Albania (355)', code: '355'},
  {value: 'Algeria', label: 'Algeria (213)', code: '213'},
  {value: 'American Samoa', label: 'American Samoa (+1-684)', code: '+1-684'},
  {value: 'Andorra', label: 'Andorra (376)', code: '376'},
  {value: 'Angola', label: 'Angola (244)', code: '244'},
  {value: 'Anguilla', label: 'Anguilla (+1-264)', code: '+1-264'},
  {value: 'Antarctica', label: 'Antarctica ()', code: ''},
  {value: 'Antigua And Barbuda', label: 'Antigua And Barbuda (+1-268)', code: '+1-268'},
  {value: 'Argentina', label: 'Argentina (54)', code: '54'},
  {value: 'Armenia', label: 'Armenia (374)', code: '374'},
  {value: 'Aruba', label: 'Aruba (297)', code: '297'},
  {value: 'Australia', label: 'Australia (61)', code: '61'},
  {value: 'Austria', label: 'Austria (43)', code: '43'},
  {value: 'Azerbaijan', label: 'Azerbaijan (994)', code: '994'},
  {value: 'Bahamas The', label: 'Bahamas The (+1-242)', code: '+1-242'},
  {value: 'Bahrain', label: 'Bahrain (973)', code: '973'},
  {value: 'Bangladesh', label: 'Bangladesh (880)', code: '880'},
  {value: 'Barbados', label: 'Barbados (+1-246)', code: '+1-246'},
  {value: 'Belarus', label: 'Belarus (375)', code: '375'},
  {value: 'Belgium', label: 'Belgium (32)', code: '32'},
  {value: 'Belize', label: 'Belize (501)', code: '501'},
  {value: 'Benin', label: 'Benin (229)', code: '229'},
  {value: 'Bermuda', label: 'Bermuda (+1-441)', code: '+1-441'},
  {value: 'Bhutan', label: 'Bhutan (975)', code: '975'},
  {value: 'Bolivia', label: 'Bolivia (591)', code: '591'},
  {
    value: 'Bonaire, Sint Eustatius and Saba',
    label: 'Bonaire, Sint Eustatius and Saba (599)',
    code: '599',
  },
  {value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina (387)', code: '387'},
  {value: 'Botswana', label: 'Botswana (267)', code: '267'},
  {value: 'Bouvet Island', label: 'Bouvet Island (55)', code: '55'},
  {value: 'Brazil', label: 'Brazil (55)', code: '55'},
  {
    value: 'British Indian Ocean Territory',
    label: 'British Indian Ocean Territory (246)',
    code: '246',
  },
  {value: 'Brunei', label: 'Brunei (673)', code: '673'},
  {value: 'Bulgaria', label: 'Bulgaria (359)', code: '359'},
  {value: 'Burkina Faso', label: 'Burkina Faso (226)', code: '226'},
  {value: 'Burundi', label: 'Burundi (257)', code: '257'},
  {value: 'Cambodia', label: 'Cambodia (855)', code: '855'},
  {value: 'Cameroon', label: 'Cameroon (237)', code: '237'},
  {value: 'Canada', label: 'Canada (1)', code: '1'},
  {value: 'Cape Verde', label: 'Cape Verde (238)', code: '238'},
  {value: 'Cayman Islands', label: 'Cayman Islands (+1-345)', code: '+1-345'},
  {value: 'Central African Republic', label: 'Central African Republic (236)', code: '236'},
  {value: 'Chad', label: 'Chad (235)', code: '235'},
  {value: 'Chile', label: 'Chile (56)', code: '56'},
  {value: 'China', label: 'China (86)', code: '86'},
  {value: 'Christmas Island', label: 'Christmas Island (61)', code: '61'},
  {value: 'Cocos (Keeling) Islands', label: 'Cocos (Keeling) Islands (61)', code: '61'},
  {value: 'Colombia', label: 'Colombia (57)', code: '57'},
  {value: 'Comoros', label: 'Comoros (269)', code: '269'},
  {value: 'Congo', label: 'Congo (242)', code: '242'},
  {
    value: 'Congo The Democratic Republic Of The',
    label: 'Congo The Democratic Republic Of The (243)',
    code: '243',
  },
  {value: 'Cook Islands', label: 'Cook Islands (682)', code: '682'},
  {value: 'Costa Rica', label: 'Costa Rica (506)', code: '506'},
  {value: "Cote D'Ivoire (Ivory Coast)", label: "Cote D'Ivoire (Ivory Coast) (225)", code: '225'},
  {value: 'Croatia (Hrvatska)', label: 'Croatia (Hrvatska) (385)', code: '385'},
  {value: 'Cuba', label: 'Cuba (53)', code: '53'},
  {value: 'Curaçao', label: 'Curaçao (599)', code: '599'},
  {value: 'Cyprus', label: 'Cyprus (357)', code: '357'},
  {value: 'Czech Republic', label: 'Czech Republic (420)', code: '420'},
  {value: 'Denmark', label: 'Denmark (45)', code: '45'},
  {value: 'Djibouti', label: 'Djibouti (253)', code: '253'},
  {value: 'Dominica', label: 'Dominica (+1-767)', code: '+1-767'},
  {
    value: 'Dominican Republic',
    label: 'Dominican Republic (+1-809 and 1-829)',
    code: '+1-809 and 1-829',
  },
  {value: 'East Timor', label: 'East Timor (670)', code: '670'},
  {value: 'Ecuador', label: 'Ecuador (593)', code: '593'},
  {value: 'Egypt', label: 'Egypt (20)', code: '20'},
  {value: 'El Salvador', label: 'El Salvador (503)', code: '503'},
  {value: 'Equatorial Guinea', label: 'Equatorial Guinea (240)', code: '240'},
  {value: 'Eritrea', label: 'Eritrea (291)', code: '291'},
  {value: 'Estonia', label: 'Estonia (372)', code: '372'},
  {value: 'Ethiopia', label: 'Ethiopia (251)', code: '251'},
  {value: 'Falkland Islands', label: 'Falkland Islands (500)', code: '500'},
  {value: 'Faroe Islands', label: 'Faroe Islands (298)', code: '298'},
  {value: 'Fiji Islands', label: 'Fiji Islands (679)', code: '679'},
  {value: 'Finland', label: 'Finland (358)', code: '358'},
  {value: 'France', label: 'France (33)', code: '33'},
  {value: 'French Guiana', label: 'French Guiana (594)', code: '594'},
  {value: 'French Polynesia', label: 'French Polynesia (689)', code: '689'},
  {value: 'French Southern Territories', label: 'French Southern Territories ()', code: ''},
  {value: 'Gabon', label: 'Gabon (241)', code: '241'},
  {value: 'Gambia The', label: 'Gambia The (220)', code: '220'},
  {value: 'Georgia', label: 'Georgia (995)', code: '995'},
  {value: 'Germany', label: 'Germany (49)', code: '49'},
  {value: 'Ghana', label: 'Ghana (233)', code: '233'},
  {value: 'Gibraltar', label: 'Gibraltar (350)', code: '350'},
  {value: 'Greece', label: 'Greece (30)', code: '30'},
  {value: 'Greenland', label: 'Greenland (299)', code: '299'},
  {value: 'Grenada', label: 'Grenada (+1-473)', code: '+1-473'},
  {value: 'Guadeloupe', label: 'Guadeloupe (590)', code: '590'},
  {value: 'Guam', label: 'Guam (+1-671)', code: '+1-671'},
  {value: 'Guatemala', label: 'Guatemala (502)', code: '502'},
  {value: 'Guernsey and Alderney', label: 'Guernsey and Alderney (+44-1481)', code: '+44-1481'},
  {value: 'Guinea', label: 'Guinea (224)', code: '224'},
  {value: 'Guinea-Bissau', label: 'Guinea-Bissau (245)', code: '245'},
  {value: 'Guyana', label: 'Guyana (592)', code: '592'},
  {value: 'Haiti', label: 'Haiti (509)', code: '509'},
  {
    value: 'Heard Island and McDonald Islands',
    label: 'Heard Island and McDonald Islands ()',
    code: '',
  },
  {value: 'Honduras', label: 'Honduras (504)', code: '504'},
  {value: 'Hong Kong S.A.R.', label: 'Hong Kong S.A.R. (852)', code: '852'},
  {value: 'Hungary', label: 'Hungary (36)', code: '36'},
  {value: 'Iceland', label: 'Iceland (354)', code: '354'},
  {value: 'India', label: 'India (91)', code: '91'},
  {value: 'Indonesia', label: 'Indonesia (62)', code: '62'},
  {value: 'Iran', label: 'Iran (98)', code: '98'},
  {value: 'Iraq', label: 'Iraq (964)', code: '964'},
  {value: 'Ireland', label: 'Ireland (353)', code: '353'},
  {value: 'Israel', label: 'Israel (972)', code: '972'},
  {value: 'Italy', label: 'Italy (39)', code: '39'},
  {value: 'Jamaica', label: 'Jamaica (+1-876)', code: '+1-876'},
  {value: 'Japan', label: 'Japan (81)', code: '81'},
  {value: 'Jersey', label: 'Jersey (+44-1534)', code: '+44-1534'},
  {value: 'Jordan', label: 'Jordan (962)', code: '962'},
  {value: 'Kazakhstan', label: 'Kazakhstan (7)', code: '7'},
  {value: 'Kenya', label: 'Kenya (254)', code: '254'},
  {value: 'Kiribati', label: 'Kiribati (686)', code: '686'},
  {value: 'Korea North', label: 'Korea North (850)', code: '850'},
  {value: 'Korea South', label: 'Korea South (82)', code: '82'},
  {value: 'Kosovo', label: 'Kosovo (383)', code: '383'},
  {value: 'Kuwait', label: 'Kuwait (965)', code: '965'},
  {value: 'Kyrgyzstan', label: 'Kyrgyzstan (996)', code: '996'},
  {value: 'Laos', label: 'Laos (856)', code: '856'},
  {value: 'Latvia', label: 'Latvia (371)', code: '371'},
  {value: 'Lebanon', label: 'Lebanon (961)', code: '961'},
  {value: 'Lesotho', label: 'Lesotho (266)', code: '266'},
  {value: 'Liberia', label: 'Liberia (231)', code: '231'},
  {value: 'Libya', label: 'Libya (218)', code: '218'},
  {value: 'Liechtenstein', label: 'Liechtenstein (423)', code: '423'},
  {value: 'Lithuania', label: 'Lithuania (370)', code: '370'},
  {value: 'Luxembourg', label: 'Luxembourg (352)', code: '352'},
  {value: 'Macau S.A.R.', label: 'Macau S.A.R. (853)', code: '853'},
  {value: 'Macedonia', label: 'Macedonia (389)', code: '389'},
  {value: 'Madagascar', label: 'Madagascar (261)', code: '261'},
  {value: 'Malawi', label: 'Malawi (265)', code: '265'},
  {value: 'Malaysia', label: 'Malaysia (60)', code: '60'},
  {value: 'Maldives', label: 'Maldives (960)', code: '960'},
  {value: 'Mali', label: 'Mali (223)', code: '223'},
  {value: 'Malta', label: 'Malta (356)', code: '356'},
  {value: 'Man (Isle of)', label: 'Man (Isle of) (+44-1624)', code: '+44-1624'},
  {value: 'Marshall Islands', label: 'Marshall Islands (692)', code: '692'},
  {value: 'Martinique', label: 'Martinique (596)', code: '596'},
  {value: 'Mauritania', label: 'Mauritania (222)', code: '222'},
  {value: 'Mauritius', label: 'Mauritius (230)', code: '230'},
  {value: 'Mayotte', label: 'Mayotte (262)', code: '262'},
  {value: 'Mexico', label: 'Mexico (52)', code: '52'},
  {value: 'Micronesia', label: 'Micronesia (691)', code: '691'},
  {value: 'Moldova', label: 'Moldova (373)', code: '373'},
  {value: 'Monaco', label: 'Monaco (377)', code: '377'},
  {value: 'Mongolia', label: 'Mongolia (976)', code: '976'},
  {value: 'Montenegro', label: 'Montenegro (382)', code: '382'},
  {value: 'Montserrat', label: 'Montserrat (+1-664)', code: '+1-664'},
  {value: 'Morocco', label: 'Morocco (212)', code: '212'},
  {value: 'Mozambique', label: 'Mozambique (258)', code: '258'},
  {value: 'Myanmar', label: 'Myanmar (95)', code: '95'},
  {value: 'Namibia', label: 'Namibia (264)', code: '264'},
  {value: 'Nauru', label: 'Nauru (674)', code: '674'},
  {value: 'Nepal', label: 'Nepal (977)', code: '977'},
  {value: 'Netherlands The', label: 'Netherlands The (31)', code: '31'},
  {value: 'New Caledonia', label: 'New Caledonia (687)', code: '687'},
  {value: 'New Zealand', label: 'New Zealand (64)', code: '64'},
  {value: 'Nicaragua', label: 'Nicaragua (505)', code: '505'},
  {value: 'Niger', label: 'Niger (227)', code: '227'},
  {value: 'Nigeria', label: 'Nigeria (234)', code: '234'},
  {value: 'Niue', label: 'Niue (683)', code: '683'},
  {value: 'Norfolk Island', label: 'Norfolk Island (672)', code: '672'},
  {value: 'Northern Mariana Islands', label: 'Northern Mariana Islands (+1-670)', code: '+1-670'},
  {value: 'Norway', label: 'Norway (47)', code: '47'},
  {value: 'Oman', label: 'Oman (968)', code: '968'},
  {value: 'Pakistan', label: 'Pakistan (92)', code: '92'},
  {value: 'Palau', label: 'Palau (680)', code: '680'},
  {
    value: 'Palestinian Territory Occupied',
    label: 'Palestinian Territory Occupied (970)',
    code: '970',
  },
  {value: 'Panama', label: 'Panama (507)', code: '507'},
  {value: 'Papua new Guinea', label: 'Papua new Guinea (675)', code: '675'},
  {value: 'Paraguay', label: 'Paraguay (595)', code: '595'},
  {value: 'Peru', label: 'Peru (51)', code: '51'},
  {value: 'Philippines', label: 'Philippines (63)', code: '63'},
  {value: 'Pitcairn Island', label: 'Pitcairn Island (870)', code: '870'},
  {value: 'Poland', label: 'Poland (48)', code: '48'},
  {value: 'Portugal', label: 'Portugal (351)', code: '351'},
  {value: 'Puerto Rico', label: 'Puerto Rico (+1-787 and 1-939)', code: '+1-787 and 1-939'},
  {value: 'Qatar', label: 'Qatar (974)', code: '974'},
  {value: 'Reunion', label: 'Reunion (262)', code: '262'},
  {value: 'Romania', label: 'Romania (40)', code: '40'},
  {value: 'Russia', label: 'Russia (7)', code: '7'},
  {value: 'Rwanda', label: 'Rwanda (250)', code: '250'},
  {value: 'Saint Helena', label: 'Saint Helena (290)', code: '290'},
  {value: 'Saint Kitts And Nevis', label: 'Saint Kitts And Nevis (+1-869)', code: '+1-869'},
  {value: 'Saint Lucia', label: 'Saint Lucia (+1-758)', code: '+1-758'},
  {value: 'Saint Pierre and Miquelon', label: 'Saint Pierre and Miquelon (508)', code: '508'},
  {
    value: 'Saint Vincent And The Grenadines',
    label: 'Saint Vincent And The Grenadines (+1-784)',
    code: '+1-784',
  },
  {value: 'Saint-Barthelemy', label: 'Saint-Barthelemy (590)', code: '590'},
  {value: 'Saint-Martin (French part)', label: 'Saint-Martin (French part) (590)', code: '590'},
  {value: 'Samoa', label: 'Samoa (685)', code: '685'},
  {value: 'San Marino', label: 'San Marino (378)', code: '378'},
  {value: 'Sao Tome and Principe', label: 'Sao Tome and Principe (239)', code: '239'},
  {value: 'Saudi Arabia', label: 'Saudi Arabia (966)', code: '966'},
  {value: 'Senegal', label: 'Senegal (221)', code: '221'},
  {value: 'Serbia', label: 'Serbia (381)', code: '381'},
  {value: 'Seychelles', label: 'Seychelles (248)', code: '248'},
  {value: 'Sierra Leone', label: 'Sierra Leone (232)', code: '232'},
  {value: 'Singapore', label: 'Singapore (65)', code: '65'},
  {value: 'Sint Maarten (Dutch part)', label: 'Sint Maarten (Dutch part) (1721)', code: '1721'},
  {value: 'Slovakia', label: 'Slovakia (421)', code: '421'},
  {value: 'Slovenia', label: 'Slovenia (386)', code: '386'},
  {value: 'Solomon Islands', label: 'Solomon Islands (677)', code: '677'},
  {value: 'Somalia', label: 'Somalia (252)', code: '252'},
  {value: 'South Africa', label: 'South Africa (27)', code: '27'},
  {value: 'South Georgia', label: 'South Georgia ()', code: ''},
  {value: 'South Sudan', label: 'South Sudan (211)', code: '211'},
  {value: 'Spain', label: 'Spain (34)', code: '34'},
  {value: 'Sri Lanka', label: 'Sri Lanka (94)', code: '94'},
  {value: 'Sudan', label: 'Sudan (249)', code: '249'},
  {value: 'Suriname', label: 'Suriname (597)', code: '597'},
  {
    value: 'Svalbard And Jan Mayen Islands',
    label: 'Svalbard And Jan Mayen Islands (47)',
    code: '47',
  },
  {value: 'Swaziland', label: 'Swaziland (268)', code: '268'},
  {value: 'Sweden', label: 'Sweden (46)', code: '46'},
  {value: 'Switzerland', label: 'Switzerland (41)', code: '41'},
  {value: 'Syria', label: 'Syria (963)', code: '963'},
  {value: 'Taiwan', label: 'Taiwan (886)', code: '886'},
  {value: 'Tajikistan', label: 'Tajikistan (992)', code: '992'},
  {value: 'Tanzania', label: 'Tanzania (255)', code: '255'},
  {value: 'Thailand', label: 'Thailand (66)', code: '66'},
  {value: 'Togo', label: 'Togo (228)', code: '228'},
  {value: 'Tokelau', label: 'Tokelau (690)', code: '690'},
  {value: 'Tonga', label: 'Tonga (676)', code: '676'},
  {value: 'Trinidad And Tobago', label: 'Trinidad And Tobago (+1-868)', code: '+1-868'},
  {value: 'Tunisia', label: 'Tunisia (216)', code: '216'},
  {value: 'Turkey', label: 'Turkey (90)', code: '90'},
  {value: 'Turkmenistan', label: 'Turkmenistan (993)', code: '993'},
  {value: 'Turks And Caicos Islands', label: 'Turks And Caicos Islands (+1-649)', code: '+1-649'},
  {value: 'Tuvalu', label: 'Tuvalu (688)', code: '688'},
  {value: 'Uganda', label: 'Uganda (256)', code: '256'},
  {value: 'Ukraine', label: 'Ukraine (380)', code: '380'},
  {value: 'United Arab Emirates', label: 'United Arab Emirates (971)', code: '971'},
  {value: 'United Kingdom', label: 'United Kingdom (44)', code: '44'},
  {value: 'United States', label: 'United States (1)', code: '1'},
  {
    value: 'United States Minor Outlying Islands',
    label: 'United States Minor Outlying Islands (1)',
    code: '1',
  },
  {value: 'Uruguay', label: 'Uruguay (598)', code: '598'},
  {value: 'Uzbekistan', label: 'Uzbekistan (998)', code: '998'},
  {value: 'Vanuatu', label: 'Vanuatu (678)', code: '678'},
  {
    value: 'Vatican City State (Holy See)',
    label: 'Vatican City State (Holy See) (379)',
    code: '379',
  },
  {value: 'Venezuela', label: 'Venezuela (58)', code: '58'},
  {value: 'Vietnam', label: 'Vietnam (84)', code: '84'},
  {value: 'Virgin Islands (British)', label: 'Virgin Islands (British) (+1-284)', code: '+1-284'},
  {value: 'Virgin Islands (US)', label: 'Virgin Islands (US) (+1-340)', code: '+1-340'},
  {value: 'Wallis And Futuna Islands', label: 'Wallis And Futuna Islands (681)', code: '681'},
  {value: 'Western Sahara', label: 'Western Sahara (212)', code: '212'},
  {value: 'Yemen', label: 'Yemen (967)', code: '967'},
  {value: 'Zambia', label: 'Zambia (260)', code: '260'},
  {value: 'Zimbabwe', label: 'Zimbabwe (263)', code: '263'},
]
